media:
 name:
 label:
 input:
 output:
 path:
 extensions:
 categories:

content:
  - name: blog
    label: Blog
    path: src/content/blog
    filename: '{year}-{month}-{day}-{fields.title}.md'
    type: collection
    view:
      fields: [heroImage, title, pubDate]
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: text
      - name: pubDate
        label: Publication Date
        type: date
        options:
          format: MM/dd/yyyy
      # ... other fields for blog posts

components:
 label:
 type:
 fields:
 component:
 description: 
 default:
 list:
 hidden: 




