html:
  lang: en
  head:
    meta:
      - charset: UTF-8
      - name: viewport
        content: width=device-width, initial-scale=1.0
    title: Suarez Professional Services | Notary & Bookkeeping Services
    meta:
      - name: description
        content: Professional notary public and bookkeeping services by Suarez Professional Services. Trusted, reliable, and professional business solutions.
    link:
      - href: https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css
        rel: stylesheet
      - rel: stylesheet
        href: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css
      - rel: stylesheet
        href: css/style.css
  body:
    nav:
      class: "navbar navbar-expand-lg navbar-dark bg-dark fixed-top"
      div:
        class: container
        a:
          class: "navbar-brand fw-bold"
          href: index.html
          i:
            class: "fas fa-briefcase me-2"
          content: Suarez Professional Services
        button:
          class: navbar-toggler
          type: button
          data-bs-toggle: collapse
          data-bs-target: "#navbarNav"
          span:
            class: navbar-toggler-icon
        div:
          class: "collapse navbar-collapse"
          id: navbarNav
          ul:
            class: "navbar-nav ms-auto"
            li:
              - class: nav-item
                a:
                  class: "nav-link active"
                  href: index.html
                  content: Home
              - class: nav-item
                a:
                  class: nav-link
                  href: notary.html
                  content: Notary Services
              - class: nav-item
                a:
                  class: nav-link
                  href: bookkeeping.html
                  content: Bookkeeping
              - class: nav-item
                a:
                  class: nav-link
                  href: contact.html
                  content: Contact
    section:
      - class: hero-section
        div:
          class: container
          div:
            class: "row align-items-center min-vh-100"
            div:
              class: col-lg-6
              div:
                class: hero-content
                h1:
                  class: "display-4 fw-bold text-white mb-4"
                  content: Professional Services You Can Trust
                p:
                  class: "lead text-light mb-4"
                  content: Providing reliable notary public and comprehensive bookkeeping services to individuals and businesses with integrity and professionalism.
                div:
                  class: "d-flex flex-column flex-sm-row gap-3"
                  a:
                    - href: contact.html
                      class: "btn btn-primary btn-lg"
                      i:
                        class: "fas fa-phone me-2"
                      content: Get Started Today
                    - href: "#services"
                      class: "btn btn-outline-light btn-lg"
                      i:
                        class: "fas fa-info-circle me-2"
                      content: Learn More
            div:
              class: col-lg-6
              div:
                class: "hero-image text-center"
                i:
                  class: "fas fa-handshake display-1 text-primary opacity-75"
      - id: services
        class: "py-5 bg-light"
        div:
          class: container
          div:
            class: row
            div:
              class: "col-12 text-center mb-5"
              h2:
                class: "display-5 fw-bold"
                content: Our Professional Services
              p:
                class: "lead text-muted"
                content: Comprehensive solutions for your business and personal needs
          div:
            class: "row g-4"
            div:
              class: col-md-6
              div:
                class: "service-card h-100 p-4 bg-white rounded shadow-sm"
                div:
                  class: "text-center mb-4"
                  i:
                    class: "fas fa-stamp display-4 text-primary mb-3"
                  h3:
                    class: "h4 fw-bold"
                    content: Notary Public Services
                ul:
                  class: "list-unstyled"
                  li:
                    - class: mb-2
                      i:
                        class: "fas fa-check text-success me-2"
                      content: Document Authentication
                    - class: mb-2
                      i:
                        class: "fas fa-check text-success me-2"
                      content: Sworn Affidavits
                    - class: mb-2
                      i:
                        class: "fas fa-check text-success me-2"
                      content: Real Estate Documents
                    - class: mb-2
                      i:
                        class: "fas fa-check text-success me-2"
                      content: Power of Attorney
                    - class: mb-2
                      i:
                        class: "fas fa-check text-success me-2"
                      content: Mobile Notary Available
                div:
                  class: "text-center mt-4"
                  a:
                    href: notary.html
                    class: "btn btn-primary"
                    i:
                      class: "fas fa-arrow-right me-2"
                    content: View Notary Services
            div:
              class: col-md-6
              div:
                class: "service-card h-100 p-4 bg-white rounded shadow-sm"
                div:
                  class: "text-center mb-4"
                  i:
                    class: "fas fa-calculator display-4 text-primary mb-3"
                  h3:
                    class: "h4 fw-bold"
                    content: Bookkeeping Services
                ul:
                  class: "list-unstyled"
                  li:
                    - class: mb-2
                      i:
                        class: "fas fa-check text-success me-2"
                      content: Financial Record Keeping
                    - class: mb-2
                      i:
                        class: "fas fa-check text-success me-2"
                      content: Tax Preparation Support
                    - class: mb-2
                      i:
                        class: "fas fa-check text-success me-2"
                      content: Payroll Processing
                    - class: mb-2
                      i:
                        class: "fas fa-check text-success me-2"
                      content: Financial Reporting
                    - class: mb-2
                      i:
                        class: "fas fa-check text-success me-2"
                      content: QuickBooks Setup & Training
                div:
                  class: "text-center mt-4"
                  a:
                    href: bookkeeping.html
                    class: "btn btn-primary"
                    i:
                      class: "fas fa-arrow-right me-2"
                    content: View Bookkeeping Services
      - class: py-5
        div:
          class: container
          div:
            class: row
            div:
              class: "col-12 text-center mb-5"
              h2:
                class: "display-5 fw-bold"
                content: Why Choose Suarez Professional Services
          div:
            class: "row g-4"
            div:
              class: "col-md-4 text-center"
              div:
                class: "feature-item p-4"
                i:
                  class: "fas fa-shield-alt display-4 text-primary mb-3"
                h4:
                  class: "fw-bold"
                  content: Trusted & Reliable
                p:
                  class: "text-muted"
                  content: Years of experience providing professional services with integrity and confidentiality.
            div:
              class: "col-md-4 text-center"
              div:
                class: "feature-item p-4"
                i:
                  class: "fas fa-clock display-4 text-primary mb-3"
                h4:
                  class: "fw-bold"
                  content: Flexible Scheduling
                p:
                  class: "text-muted"
                  content: Convenient appointment times and mobile services to meet your busy schedule.
            div:
              class: "col-md-4 text-center"
              div:
                class: "feature-item p-4"
                i:
                  class: "fas fa-dollar-sign display-4 text-primary mb-3"
                h4:
                  class: "fw-bold"
                  content: Competitive Pricing
                p:
                  class: "text-muted"
                  content: Fair, transparent pricing for all services with no hidden fees or surprises.
      - class: "py-5 bg-primary text-white"
        div:
          class: container
          div:
            class: "row justify-content-center text-center"
            div:
              class: col-lg-8
              h2:
                class: "display-5 fw-bold mb-4"
                content: Ready to Get Started?
              p:
                class: "lead mb-4"
                content: "Contact us today to discuss your notary or bookkeeping needs. We're here to provide professional, reliable service."
              a:
                href: contact.html
                class: "btn btn-light btn-lg"
                i:
                  class: "fas fa-envelope me-2"
                content: Contact Us Now
    footer:
      class: "bg-dark text-light py-4"
      div:
        class: container
        div:
          class: row
          div:
            class: col-md-6
            h5:
              class: "fw-bold mb-3"
              content: Suarez Professional Services
            p:
              class: "text-muted"
              content: Professional notary public and bookkeeping services you can trust.
          div:
            class: col-md-6
            h6:
              class: "fw-bold mb-3"
              content: Contact Information
            p:
              - class: "text-muted mb-1"
                i:
                  class: "fas fa-user me-2"
                content: Contact: Peter
              - class: "text-muted mb-1"
                i:
                  class: "fas fa-envelope me-2"
                a:
                  href: mailto:peter@suarezprofessionalservices.com
                  class: "text-muted text-decoration-none"
                  content: peter@suarezprofessionalservices.com
        hr:
          class: "my-4"
        div:
          class: row
          div:
            class: "col-12 text-center"
            p:
              class: "text-muted mb-0"
              content: "© 2025 Suarez Professional Services. All rights reserved."
    script:
      - src: https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js
      - src: js/main.js