# Pages CMS Configuration for Suarez Professional Services
# This file defines the content structure and editing interface for the CMS

# General settings
name: Suarez Professional Services
description: Professional notary and bookkeeping services CMS
logo: /favicon.ico

# Content collections
collections:
  # Site-wide settings and metadata
  - name: settings
    label: Site Settings
    description: Global site configuration and metadata
    folder: _data
    extension: yml
    format: yaml
    create: false
    fields:
      - name: site_title
        label: Site Title
        widget: string
        default: "Suarez Professional Services"
      - name: site_description
        label: Site Description
        widget: text
        default: "Professional notary public and bookkeeping services"
      - name: contact_email
        label: Contact Email
        widget: string
        default: "peter@suarezprofessionalservices.com"
      - name: phone_number
        label: Phone Number
        widget: string
        required: false
      - name: address
        label: Business Address
        widget: text
        required: false

  # Main pages content
  - name: pages
    label: Pages
    description: Main website pages content
    folder: _content/pages
    extension: yml
    format: yaml
    create: true
    slug: "{{slug}}"
    fields:
      - name: title
        label: Page Title
        widget: string
      - name: description
        label: Meta Description
        widget: text
        required: false
      - name: hero_title
        label: Hero Section Title
        widget: string
        required: false
      - name: hero_subtitle
        label: Hero Section Subtitle
        widget: text
        required: false
      - name: content_sections
        label: Content Sections
        widget: list
        fields:
          - name: section_title
            label: Section Title
            widget: string
          - name: section_content
            label: Section Content
            widget: markdown

  # Service offerings
  - name: services
    label: Services
    description: Individual service offerings
    folder: _content/services
    extension: yml
    format: yaml
    create: true
    slug: "{{slug}}"
    fields:
      - name: title
        label: Service Title
        widget: string
      - name: short_description
        label: Short Description
        widget: text
      - name: detailed_description
        label: Detailed Description
        widget: markdown
      - name: icon
        label: Font Awesome Icon Class
        widget: string
        default: "fas fa-briefcase"
        hint: "Font Awesome icon class (e.g., fas fa-stamp, fas fa-calculator)"
      - name: price_range
        label: Price Range
        widget: string
        required: false
      - name: features
        label: Service Features
        widget: list
        field:
          name: feature
          label: Feature
          widget: string
      - name: category
        label: Service Category
        widget: select
        options:
          - notary
          - bookkeeping
          - general
      - name: featured
        label: Featured Service
        widget: boolean
        default: false

  # Testimonials
  - name: testimonials
    label: Testimonials
    description: Client testimonials and reviews
    folder: _content/testimonials
    extension: yml
    format: yaml
    create: true
    slug: "{{fields.client_name}}"
    fields:
      - name: client_name
        label: Client Name
        widget: string
      - name: client_title
        label: Client Title/Company
        widget: string
        required: false
      - name: testimonial
        label: Testimonial Text
        widget: text
      - name: rating
        label: Rating (1-5 stars)
        widget: number
        value_type: int
        min: 1
        max: 5
        default: 5
      - name: service_type
        label: Service Type
        widget: select
        options:
          - notary
          - bookkeeping
          - both
      - name: featured
        label: Featured Testimonial
        widget: boolean
        default: false

  # FAQ entries
  - name: faq
    label: FAQ
    description: Frequently asked questions
    folder: _content/faq
    extension: yml
    format: yaml
    create: true
    slug: "faq-{{slug}}"
    fields:
      - name: question
        label: Question
        widget: string
      - name: answer
        label: Answer
        widget: markdown
      - name: category
        label: Category
        widget: select
        options:
          - notary
          - bookkeeping
          - general
          - pricing
      - name: order
        label: Display Order
        widget: number
        value_type: int
        default: 1

# Media settings
media_folder: assets/uploads
public_folder: /assets/uploads

# Authentication
backend:
  name: github
  repo: your-username/your-repo-name # Update with your actual GitHub repo
  branch: main
  commit_message: "Update content via Pages CMS"

# Publishing settings
publish_mode: editorial_workflow
display_url: https://your-site-url.com # Update with your actual site URL

# Development settings
local_backend: true